# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tardis-back_development

test:
  <<: *default
  database: tardis-back_test

  production:
  <<: *default
  database: tardis-back_production
  username: tardis-back
  password: <%= ENV['HACK-BACK_DATABASE_PASSWORD'] %>